"""Add authentication tables and RBAC system

Revision ID: 868fda926cd0
Revises:
Create Date: 2026-01-02 17:49:22.865189

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "868fda926cd0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "code",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column(
            "description",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column(
            "module_name",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("permission", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_permission_code"), ["code"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_permission_module_name"),
            ["module_name"],
            unique=False,
        )

    op.create_table(
        "role",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "description",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_role_name"), ["name"], unique=True
        )

    op.create_table(
        "organization_module",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "module_name",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("subscribed_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("organization_id", "module_name"),
    )
    with op.batch_alter_table("organization_module", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organization_module_is_active"),
            ["is_active"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_organization_module_organization_id"),
            ["organization_id"],
            unique=False,
        )

    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "accounts_payable",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("business_partner_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_partner_id"],
            ["business_partner.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("accounts_payable", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_accounts_payable_business_partner_id"),
            ["business_partner_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_accounts_payable_company_id"),
            ["company_id"],
            unique=False,
        )

    op.create_table(
        "accounts_receivable",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("business_partner_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_partner_id"],
            ["business_partner.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("accounts_receivable", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_accounts_receivable_business_partner_id"),
            ["business_partner_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_accounts_receivable_company_id"),
            ["company_id"],
            unique=False,
        )

    op.create_table(
        "invitation",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "token",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "email",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "EXPIRED",
                "REVOKED",
                name="invitationstatus",
            ),
            nullable=False,
        ),
        sa.Column("invited_by", sa.Uuid(), nullable=False),
        sa.Column("accepted_by", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column(
            "default_role",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("invitation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invitation_email"), ["email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_invitation_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_invitation_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_invitation_token"), ["token"], unique=True
        )

    op.create_table(
        "oauth_account",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "oauth_name",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column(
            "access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("expires_at", sa.Integer(), nullable=True),
        sa.Column(
            "refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "account_id",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column(
            "account_email",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("oauth_account", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_oauth_account_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_permission",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "permission_id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "hashed_password",
                sqlmodel.sql.sqltypes.AutoString(length=255),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_superuser",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_verified",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    with op.batch_alter_table("user_company_access", schema=None) as batch_op:
        batch_op.add_column(sa.Column("role_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, "role", ["role_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_company_access", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("role_id")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("is_verified")
        batch_op.drop_column("is_superuser")
        batch_op.drop_column("hashed_password")

    op.drop_table("user_permission")
    with op.batch_alter_table("oauth_account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_account_user_id"))

    op.drop_table("oauth_account")
    with op.batch_alter_table("invitation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invitation_token"))
        batch_op.drop_index(batch_op.f("ix_invitation_status"))
        batch_op.drop_index(batch_op.f("ix_invitation_organization_id"))
        batch_op.drop_index(batch_op.f("ix_invitation_email"))

    op.drop_table("invitation")
    with op.batch_alter_table("accounts_receivable", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_receivable_company_id"))
        batch_op.drop_index(
            batch_op.f("ix_accounts_receivable_business_partner_id")
        )

    op.drop_table("accounts_receivable")
    with op.batch_alter_table("accounts_payable", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_payable_company_id"))
        batch_op.drop_index(
            batch_op.f("ix_accounts_payable_business_partner_id")
        )

    op.drop_table("accounts_payable")
    op.drop_table("role_permission")
    with op.batch_alter_table("organization_module", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_organization_module_organization_id")
        )
        batch_op.drop_index(batch_op.f("ix_organization_module_is_active"))

    op.drop_table("organization_module")
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_name"))

    op.drop_table("role")
    with op.batch_alter_table("permission", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permission_module_name"))
        batch_op.drop_index(batch_op.f("ix_permission_code"))

    op.drop_table("permission")
    # ### end Alembic commands ###
